spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1/${PG_DATABASE}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: easyroadmap.agent
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
    test-connection: true

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    '[org.springframework.web]': DEBUG
    '[org.springframework.security]': DEBUG
  pattern:
    console: '%clr([){faint}%clr(%d{dd.MM.yy}){faint} %clr(%d{HH:mm:ss}){magenta}%clr(]){faint} %clr(%5p) %clr(:){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %m%n%wEx'

server:
  servlet:
    session:
      cookie:
        same-site: lax

  auth:
    default-redirect-url: http://localhost:8080/workspace

  cors:
    allowed-origin: "http://localhost:8080"

  error:
    whitelabel:
      enabled: false
    path: /error

  host: http://localhost:8080

  mail:
    name: EasyRoadMap
    address: easyroadmap.agent@gmail.com

  storage:
    data-directory: 'data'

springdoc:
  api-docs:
    path: /docs/openapi
  swagger-ui:
    operations-sorter: alpha
    path: /docs/swagger
    url: /docs/openapi
