spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1/${PG_DATABASE}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

  mail:
    host: 127.0.0.1
    port: 25
    username: no-reply
    password: no-reply
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: false
    test-connection: true

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    '[org.springframework.web]': DEBUG
    '[org.springframework.security]': DEBUG
  file:
    name: 'logs/easyroadmap.log'
  logback:
    rollingpolicy:
      max-history: 50
  pattern:
    console: '%clr([){faint}%clr(%d{dd.MM.yy}){faint} %clr(%d{HH:mm:ss}){magenta}%clr(]){faint} %clr(%5p) %clr(:){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %m%n%wEx'
    file: '[%d{dd.MM.yy / HH:mm:ss.SSS}] %5p ${PID:-} --- [%t] %-40.40logger{39} : %m%n%wEx'

server:
  servlet:
    session:
      cookie:
        same-site: lax

  auth:
    default-redirect-url: https://easyroadmap.ru/workspace

  cors:
    allowed-origin: "https://easyroadmap.ru"

  error:
    whitelabel:
      enabled: false
    path: /error

  host: https://easyroadmap.ru

  mail:
    name: EasyRoadMap
    address: no-reply@easyroadmap.ru

  storage:
    data-directory: 'data'

springdoc:
  api-docs:
    path: /docs/openapi
  swagger-ui:
    operations-sorter: method
    path: /docs/swagger
    url: /docs/openapi
